# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProyectoUnoVentana.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class ProyectoUno(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTitulo = QtWidgets.QLabel(self.centralwidget)
        self.lblTitulo.setGeometry(QtCore.QRect(270, 10, 221, 41))
        self.lblTitulo.setObjectName("lblTitulo")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 40, 741, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lblDNI = QtWidgets.QLabel(self.centralwidget)
        self.lblDNI.setGeometry(QtCore.QRect(80, 80, 31, 21))
        self.lblDNI.setObjectName("lblDNI")
        self.lblNombre = QtWidgets.QLabel(self.centralwidget)
        self.lblNombre.setGeometry(QtCore.QRect(390, 120, 61, 21))
        self.lblNombre.setObjectName("lblNombre")
        self.lblApellidos = QtWidgets.QLabel(self.centralwidget)
        self.lblApellidos.setGeometry(QtCore.QRect(80, 120, 61, 21))
        self.lblApellidos.setObjectName("lblApellidos")
        self.leDNI = QtWidgets.QLineEdit(self.centralwidget)
        self.leDNI.setGeometry(QtCore.QRect(120, 80, 113, 20))
        self.leDNI.setObjectName("leDNI")
        self.leNombre = QtWidgets.QLineEdit(self.centralwidget)
        self.leNombre.setGeometry(QtCore.QRect(450, 120, 113, 20))
        self.leNombre.setObjectName("leNombre")
        self.leApellidos = QtWidgets.QLineEdit(self.centralwidget)
        self.leApellidos.setGeometry(QtCore.QRect(140, 120, 113, 20))
        self.leApellidos.setObjectName("leApellidos")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 320, 741, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.btAceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btAceptar.setGeometry(QtCore.QRect(250, 350, 75, 23))
        self.btAceptar.setObjectName("btAceptar")
        self.btSalir = QtWidgets.QPushButton(self.centralwidget)
        self.btSalir.setGeometry(QtCore.QRect(400, 350, 75, 23))
        self.btSalir.setObjectName("btSalir")
        self.lblValidarDNI = QtWidgets.QLabel(self.centralwidget)
        self.lblValidarDNI.setGeometry(QtCore.QRect(250, 80, 47, 21))
        self.lblValidarDNI.setText("")
        self.lblValidarDNI.setObjectName("lblValidarDNI")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.menuArchivo.addAction(self.actionSalir)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTitulo.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">XESTIÓN CLIENTES</span></p></body></html>"))
        self.lblDNI.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">DNI:</span></p></body></html>"))
        self.lblNombre.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Nome:</span></p></body></html>"))
        self.lblApellidos.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Apelidos:</span></p></body></html>"))
        self.btAceptar.setText(_translate("MainWindow", "Aceptar"))
        self.btSalir.setText(_translate("MainWindow", "Salir"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionSalir.setShortcut(_translate("MainWindow", "Alt+4"))
