# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaaviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-50, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.labelImagenAviso = QtWidgets.QLabel(Dialog)
        self.labelImagenAviso.setGeometry(QtCore.QRect(140, 50, 121, 101))
        self.labelImagenAviso.setText("")
        self.labelImagenAviso.setPixmap(QtGui.QPixmap("warning.png"))
        self.labelImagenAviso.setScaledContents(True)
        self.labelImagenAviso.setObjectName("labelImagenAviso")
        self.labelPregunta = QtWidgets.QLabel(Dialog)
        self.labelPregunta.setGeometry(QtCore.QRect(130, 170, 141, 31))
        self.labelPregunta.setObjectName("labelPregunta")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Aviso"))
        self.labelPregunta.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">¿Desea salir?</span></p></body></html>"))
