# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaavisomenor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-110, 230, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.labelImagen = QtWidgets.QLabel(Dialog)
        self.labelImagen.setGeometry(QtCore.QRect(40, 100, 81, 71))
        self.labelImagen.setText("")
        self.labelImagen.setPixmap(QtGui.QPixmap("warning.png"))
        self.labelImagen.setScaledContents(True)
        self.labelImagen.setObjectName("labelImagen")
        self.labelAviso = QtWidgets.QLabel(Dialog)
        self.labelAviso.setGeometry(QtCore.QRect(120, 110, 251, 71))
        self.labelAviso.setObjectName("labelAviso")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Aviso Menor de Edad"))
        self.labelAviso.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">ES MENOR DE EDAD</span></p><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">NO PUEDE REALIZAR LA OPERACIÓN</span></p></body></html>"))
